
import { Decimal } from 'decimal.js'; // Added Decimal import
import { CollectibleEggDefinition, CollectibleEggDisplayRarity } from '../types';

export const COLLECTIBLE_EGG_DEFINITIONS: CollectibleEggDefinition[] = [
  {
    id: 'collectible_draconicEgg',
    name: 'Ovo Dracônico',
    type: 'Dano',
    abilityDefinitionIds: ['ab_draconic_fireball', 'ab_draconic_tail_sweep'],
    personality: 'Agressivo',
    icon: 'fas fa-dragon text-red-500',
    description: 'Um ovo escamoso que pulsa com poder elemental de fogo. Parece guardar segredos antigos.',
    rarity: 'Raro',
    baseStats: { hpMax: 120, attack: 18, defense: 10, speed: 12, resourceMax: 50, resourceName: 'Fúria' },
  },
  {
    id: 'collectible_voidEgg',
    name: 'Ovo do Vazio',
    type: 'Suporte',
    abilityDefinitionIds: ['ab_void_mind_blast', 'ab_void_energy_siphon'],
    personality: 'Calculista',
    icon: 'fas fa-atom text-purple-500',
    description: 'Um ovo enigmático que parece dobrar as energias ao seu redor, sussurrando sobre o potencial.',
    rarity: 'Lendário',
    baseStats: { hpMax: 90, attack: 10, defense: 14, speed: 14, resourceMax: 70, resourceName: 'Mana' },
  },
  {
    id: 'collectible_rockEgg',
    name: 'Ovo Rochoso',
    type: 'Tanque',
    abilityDefinitionIds: ['ab_rock_harden_shell', 'ab_rock_quake_stomp'],
    personality: 'Protetor',
    icon: 'fas fa-mountain text-yellow-700',
    description: 'Um ovo pesado e resistente, com uma superfície que lembra granito bruto.',
    rarity: 'Comum',
    baseStats: { hpMax: 180, attack: 8, defense: 22, speed: 7, resourceMax: 30, resourceName: 'Vigor' },
  },
  {
    id: 'collectible_stormEgg',
    name: 'Ovo Tempestuoso',
    type: 'Dano/Controle',
    abilityDefinitionIds: ['ab_basic_attack', 'ab_strong_hit'], 
    personality: 'Impulsivo',
    icon: 'fas fa-wind text-sky-400',
    description: 'Energia crepita ao redor deste ovo, que parece inquieto e pronto para explodir.',
    rarity: 'Raro',
    baseStats: { hpMax: 100, attack: 15, defense: 8, speed: 16, resourceMax: 60, resourceName: 'Energia' },
  },
  {
    id: 'collectible_starEgg',
    name: 'Ovo Estelar',
    type: 'Suporte/Dano',
    abilityDefinitionIds: ['ab_minor_heal', 'ab_team_heal_small'], 
    personality: 'Sábio',
    icon: 'fas fa-star text-yellow-300',
    description: 'Fragmentos de estrelas parecem incrustados em sua casca, emanando uma luz suave e poderosa.',
    rarity: 'Mítico',
    baseStats: { hpMax: 130, attack: 12, defense: 12, speed: 13, resourceMax: 80, resourceName: 'Luz' },
  },
  {
    id: 'collectible_fungalEgg',
    name: 'Ovo Fúngico',
    type: 'Suporte/Controle',
    abilityDefinitionIds: ['ab_fungal_paralyzing_spores', 'ab_fungal_mycelial_infestation'],
    personality: 'Caótico',
    icon: 'fas fa-disease text-lime-600', 
    description: 'A casca esporulenta deste ovo pulsa com uma energia viva e parasitária. Ele parece respirar sozinho.',
    rarity: 'Raro',
    baseStats: { hpMax: 110, attack: 9, defense: 14, speed: 11, resourceMax: 60, resourceName: 'Esporos' },
  },
  {
    id: 'collectible_bladesEgg',
    name: 'Ovo das Lâminas',
    type: 'Dano Puro',
    abilityDefinitionIds: ['ab_blades_quick_cut', 'ab_blades_unstable_blade'],
    personality: 'Impulsivo',
    icon: 'fas fa-bomb text-slate-400', 
    description: 'Sua casca parece feita de metal vivo, afiando-se com o tempo. Este ovo é pura agressão.',
    rarity: 'Raro',
    baseStats: { hpMax: 100, attack: 20, defense: 9, speed: 14, resourceMax: 40, resourceName: 'Frenesi' },
  },
  {
    id: 'collectible_necroticEgg',
    name: 'Ovo Necrótico',
    type: 'Dano/Controle',
    abilityDefinitionIds: ['ab_necrotic_entropy_touch', 'ab_necrotic_evoke_ghoul'],
    personality: 'Calculista',
    icon: 'fas fa-skull-crossbones text-purple-700',
    description: 'Este ovo tem uma aura mórbida e fria, como se a morte se alimentasse dele.',
    rarity: 'Lendário',
    baseStats: { hpMax: 95, attack: 16, defense: 13, speed: 12, resourceMax: 65, resourceName: 'Essência Sombria' },
  },
  {
    id: 'collectible_floralEgg',
    name: 'Ovo Florálgico',
    type: 'Suporte/Cura',
    abilityDefinitionIds: ['ab_floral_pollen_rain', 'ab_floral_protective_roots'],
    personality: 'Protetor',
    icon: 'fas fa-spa text-pink-400', 
    description: 'Uma energia pacífica e restauradora emana deste ovo, como a brisa de uma floresta sagrada.',
    rarity: 'Mítico', // Changed from Épico to Mítico as per prompt example for rarities
    baseStats: { hpMax: 140, attack: 6, defense: 16, speed: 10, resourceMax: 70, resourceName: 'Seiva' },
  },
  {
    id: 'collectible_glacialEgg',
    name: 'Ovo Glacial',
    type: 'Controle/Tanque',
    abilityDefinitionIds: ['ab_glacial_freezing_frost', 'ab_glacial_ice_wall'],
    personality: 'Sábio',
    icon: 'fas fa-snowflake text-blue-300',
    description: 'Gélido ao toque, este ovo parece conter um inverno inteiro. Seu núcleo brilha como uma geleira viva.',
    rarity: 'Mítico', // Changed from Épico to Mítico as per prompt example for rarities
    baseStats: { hpMax: 160, attack: 10, defense: 20, speed: 8, resourceMax: 50, resourceName: 'Gelo' },
  },
  {
    id: 'collectible_mirroredEgg',
    name: 'Ovo Espelhado',
    type: 'Controle/Suporte',
    abilityDefinitionIds: ['ab_mirrored_instinctive_reflection', 'ab_mirrored_energy_mirror'],
    personality: 'Sábio',
    icon: 'fas fa-circle-half-stroke text-cyan-400',
    description: 'A casca reflexiva desse ovo parece reproduzir os movimentos de quem o encara. Misterioso e imprevisível.',
    rarity: 'Raro',
    baseStats: { hpMax: 115, attack: 10, defense: 11, speed: 12, resourceMax: 60, resourceName: 'Reflexo' },
  },
  {
    id: 'collectible_volcanicEgg',
    name: 'Ovo Vulcânico',
    type: 'Dano em Área',
    abilityDefinitionIds: ['ab_volcanic_eruption', 'ab_volcanic_magma_fissure'],
    personality: 'Agressivo',
    icon: 'fas fa-fire text-orange-600',
    description: 'Um calor abrasador escapa por pequenas fissuras em sua casca. Ele pulsa como um vulcão prestes a explodir.',
    rarity: 'Épico',
    baseStats: { hpMax: 105, attack: 22, defense: 8, speed: 9, resourceMax: 50, resourceName: 'Magma' },
  },
  {
    id: 'collectible_illusoryEgg',
    name: 'Ovo Ilusório',
    type: 'Controle/Mitigação',
    abilityDefinitionIds: ['ab_illusory_visual_distortion', 'ab_illusory_image_refraction'],
    personality: 'Caótico',
    icon: 'fas fa-eye-slash text-indigo-400',
    description: 'Impossível focar nele por muito tempo. Sua casca muda sutilmente a forma, como se não estivesse realmente ali.',
    rarity: 'Raro',
    baseStats: { hpMax: 100, attack: 9, defense: 11, speed: 17, resourceMax: 70, resourceName: 'Névoa' },
  },
  {
    id: 'collectible_radioactiveEgg',
    name: 'Ovo Radioativo',
    type: 'Dano Persistente / Debuff',
    abilityDefinitionIds: ['ab_radioactive_toxic_pulse', 'ab_radioactive_unstable_fusion'],
    personality: 'Calculista',
    icon: 'fas fa-radiation text-green-500',
    description: 'Emite um brilho esverdeado instável. Algo dentro se move, mesmo sem vida.',
    rarity: 'Lendário',
    baseStats: { hpMax: 95, attack: 12, defense: 10, speed: 13, resourceMax: 60, resourceName: 'Radiação' },
  },
  {
    id: 'collectible_nocturnalEgg',
    name: 'Ovo Noturno',
    type: 'Controle/Apoio Sombrio',
    abilityDefinitionIds: ['ab_nocturnal_binding_shadow', 'ab_nocturnal_twilight_flight'],
    personality: 'Sombrio',
    icon: 'fas fa-moon text-slate-500',
    description: 'A luz desaparece ao redor desse ovo. Há um sussurro constante, como um lamento distante.',
    rarity: 'Épico',
    baseStats: { hpMax: 110, attack: 13, defense: 14, speed: 15, resourceMax: 50, resourceName: 'Trevas' },
  },
  // Common Eggs from previous addition
  {
    id: 'collectible_gravelEgg',
    name: 'Ovo de Cascalho',
    type: 'Tanque / Dano',
    abilityDefinitionIds: ['ab_gravel_rolling_impact', 'ab_gravel_rustic_fortification'],
    personality: 'Persistente',
    icon: 'fas fa-gem text-stone-500',
    description: 'Um ovo pequeno, irregular e duro como pedra de rio. Seu interior vibra com energia geológica bruta.',
    rarity: 'Comum',
    baseStats: { hpMax: 150, attack: 10, defense: 18, speed: 8, resourceMax: 40, resourceName: 'Vigor' },
  },
  {
    id: 'collectible_sproutEgg',
    name: 'Ovo Broto',
    type: 'Suporte leve',
    abilityDefinitionIds: ['ab_sprout_healing_dew', 'ab_sprout_invigorating_seed'],
    personality: 'Gentil',
    icon: 'fas fa-leaf text-lime-500',
    description: 'Coberto por uma película verde e úmida, este ovo parece germinar vida onde toca.',
    rarity: 'Comum',
    baseStats: { hpMax: 130, attack: 6, defense: 10, speed: 11, resourceMax: 50, resourceName: 'Seiva' },
  },
  {
    id: 'collectible_kineticEgg',
    name: 'Ovo Cinético',
    type: 'Dano rápido',
    abilityDefinitionIds: ['ab_kinetic_sudden_burst', 'ab_kinetic_rapid_displacement'],
    personality: 'Hiperativo',
    icon: 'fas fa-bolt text-yellow-400',
    description: 'Sempre em movimento, este ovo treme com velocidade e instabilidade.',
    rarity: 'Comum',
    baseStats: { hpMax: 90, attack: 14, defense: 7, speed: 18, resourceMax: 50, resourceName: 'Energia' },
  },
  {
    id: 'collectible_coralEgg',
    name: 'Ovo de Coral',
    type: 'Tanque Suporte',
    abilityDefinitionIds: ['ab_coral_protective_mantle', 'ab_coral_saline_resonance'],
    personality: 'Passivo',
    icon: 'fas fa-fan text-teal-400',
    description: 'Seu exterior é feito de estruturas marinhas endurecidas. Um eco oceânico vibra em seu interior.',
    rarity: 'Comum',
    baseStats: { hpMax: 160, attack: 7, defense: 19, speed: 7, resourceMax: 40, resourceName: 'Maré' },
  },
  {
    id: 'collectible_marrowEgg',
    name: 'Ovo de Medula',
    type: 'Dano/Status',
    abilityDefinitionIds: ['ab_marrow_instinctive_strike', 'ab_marrow_danger_alert'],
    personality: 'Instintivo',
    icon: 'fas fa-bone text-gray-300',
    description: 'Tem uma casca opaca e esbranquiçada. Há algo ancestral e rudimentar em sua estrutura.',
    rarity: 'Comum',
    baseStats: { hpMax: 110, attack: 12, defense: 9, speed: 10, resourceMax: 50, resourceName: 'Instinto' },
  },
  // New "Uncommon" (Raro) Eggs
  {
    id: 'collectible_whisperingEgg',
    name: 'Ovo Sussurrante',
    type: 'Controle Mental',
    abilityDefinitionIds: ['ab_whisper_dream_confusion', 'ab_whisper_mental_residue'],
    personality: 'Enigmático',
    icon: 'fas fa-comment-dots text-indigo-400',
    description: 'Constantemente emite ruídos suaves e pulsos de energia psiônica. Dizem que quem ouve de perto sonha com o futuro.',
    rarity: 'Raro',
    baseStats: { hpMax: 100, attack: 9, defense: 12, speed: 13, resourceMax: 60, resourceName: 'Eco Psíquico' },
  },
  {
    id: 'collectible_skeletalEgg',
    name: 'Ovo Esquelético',
    type: 'Dano / Status',
    abilityDefinitionIds: ['ab_skeletal_ghost_tooth', 'ab_skeletal_cracked_shell'],
    personality: 'Amargurado',
    icon: 'fas fa-bone text-neutral-400',
    description: 'Rígido, de casca fina e pálida, remanescente de algo que já morreu, mas se recusa a descansar.',
    rarity: 'Raro',
    baseStats: { hpMax: 105, attack: 14, defense: 10, speed: 11, resourceMax: 50, resourceName: 'Necroenergia' },
  },
  {
    id: 'collectible_mossEgg',
    name: 'Ovo de Musgo',
    type: 'Suporte Regenerativo',
    abilityDefinitionIds: ['ab_moss_regrowth', 'ab_moss_mossy_grip'],
    personality: 'Paciente',
    icon: 'fas fa-seedling text-green-600',
    description: 'Quente e úmido ao toque, parece estar em simbiose com pequenos organismos. Traz paz, mas esconde força.',
    rarity: 'Raro',
    baseStats: { hpMax: 140, attack: 7, defense: 15, speed: 8, resourceMax: 60, resourceName: 'Seiva Viva' },
  },
  {
    id: 'collectible_sparkingEgg',
    name: 'Ovo da Centelha',
    type: 'Dano Rápido / Crítico',
    abilityDefinitionIds: ['ab_spark_accelerated_discharge', 'ab_spark_electric_crackle'],
    personality: 'Temperamental',
    icon: 'fas fa-bolt text-yellow-500',
    description: 'Vibra com pequenas descargas elétricas. É instável, veloz e explode com energia quando tocado.',
    rarity: 'Raro',
    baseStats: { hpMax: 95, attack: 17, defense: 7, speed: 16, resourceMax: 50, resourceName: 'Carga' },
  },
  {
    id: 'collectible_petrifiedEgg',
    name: 'Ovo Petrificado',
    type: 'Tanque / Status',
    abilityDefinitionIds: ['ab_petrified_active_immobility', 'ab_petrified_basalt_shell'],
    personality: 'Impassível',
    icon: 'fas fa-gem text-stone-600',
    description: 'Imóvel, compacto, denso. Seu tempo de reação é lento, mas sua resistência é absurda.',
    rarity: 'Raro',
    baseStats: { hpMax: 170, attack: 6, defense: 25, speed: 5, resourceMax: 40, resourceName: 'Rocha Interna' },
  },
  // New Epic Eggs
  {
    id: 'collectible_containedLightningEgg',
    name: 'Ovo do Raio Contido',
    type: 'Dano em Cadeia / Controle',
    abilityDefinitionIds: ['ab_lightning_chain_shot', 'ab_lightning_paralytic_shock'],
    personality: 'Impulsivo',
    icon: 'fas fa-bullseye text-yellow-400',
    description: 'Sua casca vibra com energia elétrica comprimida. Estalos cortam o ar à sua volta.',
    rarity: 'Épico',
    baseStats: { hpMax: 105, attack: 18, defense: 9, speed: 17, resourceMax: 70, resourceName: 'Carga' },
  },
  {
    id: 'collectible_umbralEgg',
    name: 'Ovo Umbroso',
    type: 'Debuff / Mitigação',
    abilityDefinitionIds: ['ab_umbral_shadow_cover', 'ab_umbral_light_drain'],
    personality: 'Sutil',
    icon: 'fas fa-circle-half-stroke text-slate-600',
    description: 'Envolto em trevas líquidas, sua silhueta mal é visível. Sua presença evoca instabilidade.',
    rarity: 'Épico',
    baseStats: { hpMax: 115, attack: 11, defense: 14, speed: 13, resourceMax: 65, resourceName: 'Sombra' },
  },
  {
    id: 'collectible_psychicEgg',
    name: 'Ovo Psíquico',
    type: 'Controle Mental / Utility',
    abilityDefinitionIds: ['ab_psychic_neural_confusion', 'ab_psychic_clairvoyance'],
    personality: 'Calculista',
    icon: 'fas fa-brain text-purple-400',
    description: 'Um zumbido psíquico ressoa ao seu redor. Parece saber o que você vai fazer antes mesmo de agir.',
    rarity: 'Épico',
    baseStats: { hpMax: 100, attack: 14, defense: 11, speed: 16, resourceMax: 80, resourceName: 'Psi' },
  },
  {
    id: 'collectible_obsidianEgg',
    name: 'Ovo Obsidiano',
    type: 'Tanque / Contra-Ataque',
    abilityDefinitionIds: ['ab_obsidian_reflection', 'ab_obsidian_contained_fury'],
    personality: 'Resoluto',
    icon: 'fas fa-gem text-neutral-800',
    description: 'Sua superfície negra e brilhante é quase inquebrável. Um núcleo rubro pulsa em seu interior.',
    rarity: 'Épico',
    baseStats: { hpMax: 170, attack: 12, defense: 24, speed: 8, resourceMax: 40, resourceName: 'Tenacidade' },
  },
  {
    id: 'collectible_vortexEgg',
    name: 'Ovo do Vórtice',
    type: 'Dano em Massa / Imprevisível',
    abilityDefinitionIds: ['ab_vortex_chaotic_swirl', 'ab_vortex_discharge'],
    personality: 'Caótico',
    icon: 'fas fa-circle-notch fa-spin text-cyan-400',
    description: 'Parece girar continuamente, mesmo em repouso. Sua energia é instável e difícil de conter.',
    rarity: 'Épico',
    baseStats: { hpMax: 120, attack: 17, defense: 10, speed: 14, resourceMax: 60, resourceName: 'Impulso' },
  },
  // New Legendary Eggs
  {
    id: 'collectible_chronoSpiralEgg',
    name: 'Ovo Cronoespiral',
    type: 'Suporte/Tático',
    abilityDefinitionIds: ['ab_chrono_rewind', 'ab_chrono_anomaly'],
    personality: 'Visionário',
    icon: 'fas fa-hourglass-half text-cyan-300',
    description: 'Sua casca é marcada por fissuras temporais que revelam eventos passados e futuros. Gira levemente contra o tempo. Passiva: Ao morrer, volta com 30% da vida uma vez por combate.',
    rarity: 'Lendário',
    baseStats: { hpMax: 105, attack: 11, defense: 14, speed: 17, resourceMax: 60, resourceName: 'Tempo' },
  },
  {
    id: 'collectible_imprisonedRuinEgg',
    name: 'Ovo da Ruína Enclausurada',
    type: 'Dano em Escalada / Debuff',
    abilityDefinitionIds: ['ab_ruin_growing_corruption', 'ab_ruin_cadaveric_explosion'],
    personality: 'Sádico',
    icon: 'fas fa-skull-crossbones text-red-700',
    description: 'Um ovo trincado com energia necro-psíquica selada. Seu interior pulsa como uma prisão viva. Passiva: Ganha +5 Ataque a cada inimigo que morre no combate.',
    rarity: 'Lendário',
    baseStats: { hpMax: 95, attack: 20, defense: 9, speed: 13, resourceMax: 70, resourceName: 'Corrupção' },
  },
  {
    id: 'collectible_trueAbyssalEgg',
    name: 'Ovo Abismal (Verdadeiro)',
    type: 'Dano/Controle Brutal',
    abilityDefinitionIds: ['ab_abyssal_gaze', 'ab_abyssal_entropy'],
    personality: 'Sombrio',
    icon: 'fas fa-water text-indigo-700',
    description: 'A casca opaca deste ovo parece sugar luz, som e esperança. Ele não apenas fere — ele apaga. Passiva: Inimigos com menos de 30% de vida recebem 25% mais dano deste Ovo.',
    rarity: 'Lendário',
    baseStats: { hpMax: 100, attack: 21, defense: 10, speed: 12, resourceMax: 70, resourceName: 'Essência Abissal' },
  },
  {
    id: 'collectible_chimericEgg',
    name: 'Ovo Quimérico',
    type: 'Mutável/Surpresa',
    abilityDefinitionIds: ['ab_chimera_random_mutation', 'ab_chimera_charge'],
    personality: 'Caótico',
    icon: 'fas fa-shuffle text-pink-600',
    description: 'Um ovo instável que muda de forma e comportamento a cada combate. Passiva: Ao morrer, causa 10 de dano a todos os inimigos e aplica um debuff aleatório neles.',
    rarity: 'Lendário',
    baseStats: { hpMax: 105, attack: 16, defense: 12, speed: 15, resourceMax: 60, resourceName: 'Impulso' },
  },
];

// export const CLICKS_PER_COLLECTIBLE_EGG = 10; // Removed
export const EGG_FRAGMENTS_PER_CLICK = new Decimal(1);
export const EGG_FRAGMENTS_FOR_RANDOM_ROLL = new Decimal(500);
export const REROLL_COST_ET = new Decimal(10);
export const MAX_ACQUISITION_HISTORY = 5;

export const COLLECTIBLE_EGG_RARITY_CHANCES: { rarity: CollectibleEggDisplayRarity, chance: number }[] = [
  { rarity: 'Comum', chance: 0.55 }, // Adjusted chances
  { rarity: 'Raro', chance: 0.30 }, // "Incomum" eggs increase the pool of Rares
  { rarity: 'Épico', chance: 0.09 },
  { rarity: 'Lendário', chance: 0.04 },
  { rarity: 'Mítico', chance: 0.02 },
];

export const FIXED_EGG_SHOP_COSTS: Record<CollectibleEggDisplayRarity, Decimal> = {
  'Comum': new Decimal(750), 
  'Raro': new Decimal(1500),
  'Épico': new Decimal(3000),
  'Lendário': new Decimal(5000),
  'Mítico': new Decimal(10000),
};