import { Decimal } from 'decimal.js';
import { BattleStatusEffectDefinition } from '../types';

export const STATUS_EFFECT_DEFINITIONS: BattleStatusEffectDefinition[] = [
  // --- Debuffs ---
  {
    id: 'se_burn_dot_minor',
    name: 'Queimadura Menor',
    description: 'Sofre 5 de dano de fogo no início do seu turno.',
    icon: 'fas fa-fire text-orange-400',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 3,
    baseTickValue: new Decimal(5),
    tickIntervalTurns: 1,
  },
  {
    id: 'se_burn_dot_medium', // New
    name: 'Queimadura (M)',
    description: 'Sofre 8 de dano de fogo no início do seu turno.',
    icon: 'fas fa-fire-alt text-orange-500',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 2,
    baseTickValue: new Decimal(8),
    tickIntervalTurns: 1,
  },
  {
    id: 'se_defense_debuff_minor',
    name: 'Defesa Reduzida (P)',
    description: 'Defesa reduzida em 20%.',
    icon: 'fas fa-shield-alt text-red-400 opacity-70',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(-0.20),
    baseDurationTurns: 3,
  },
  {
    id: 'se_speed_debuff_minor',
    name: 'Velocidade Reduzida (P)',
    description: 'Velocidade reduzida em 20%.',
    icon: 'fas fa-person-running text-blue-400 opacity-70', 
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'speed',
    changeValue: new Decimal(-0.20),
    baseDurationTurns: 2,
  },
  {
    id: 'se_speed_debuff_major', // New
    name: 'Velocidade Reduzida (G)',
    description: 'Velocidade reduzida em 40%.',
    icon: 'fas fa-person-running text-blue-600 opacity-80', 
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'speed',
    changeValue: new Decimal(-0.40),
    baseDurationTurns: 3,
  },
  {
    id: 'se_stun_short',
    name: 'Atordoado',
    description: 'Não pode realizar ações neste turno.',
    icon: 'fas fa-star text-yellow-500 animate-ping',
    type: 'debuff',
    effectType: 'stun',
    baseDurationTurns: 1,
  },
  {
    id: 'se_rooted_ability_lock',
    name: 'Enraizado',
    description: 'Não pode usar habilidades especiais por 1 turno.',
    icon: 'fas fa-tree text-green-700',
    type: 'debuff',
    effectType: 'ability_lock',
    baseDurationTurns: 1,
  },
  {
    id: 'se_silence_ability_lock', // New
    name: 'Silenciado',
    description: 'Não pode usar habilidades.',
    icon: 'fas fa-microphone-slash text-gray-500',
    type: 'debuff',
    effectType: 'ability_lock',
    baseDurationTurns: 2, 
  },
  {
    id: 'se_infested_dot',
    name: 'Infestado',
    description: 'Sofre 4 de dano por turno por 4 turnos.', // Resource drain handled by ability directly for now
    icon: 'fas fa-bacteria text-lime-500',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 4,
    baseTickValue: new Decimal(4),
    tickIntervalTurns: 1,
  },
  {
    id: 'se_radiated_dot_resource_degen', // New
    name: 'Radiado',
    description: 'Sofre 5 de dano e perde um pouco de recurso no início do turno.', // Simplified resource degen
    icon: 'fas fa-radiation text-yellow-400',
    type: 'debuff',
    effectType: 'damage_over_time', // Resource part handled by ability/main loop
    baseDurationTurns: 4,
    baseTickValue: new Decimal(5),
    tickIntervalTurns: 1,
  },
  {
    id: 'se_bleeding_dot',
    name: 'Sangramento',
    description: 'Sofre 3 de dano por turno por 3 turnos.',
    icon: 'fas fa-tint text-red-700',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 3,
    baseTickValue: new Decimal(3),
    tickIntervalTurns: 1,
  },
  {
    id: 'se_weakened_attack_debuff',
    name: 'Enfraquecido',
    description: 'Ataque reduzido em 25%.',
    icon: 'fas fa-hand-fist text-slate-400 opacity-70',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(-0.25),
    baseDurationTurns: 2,
  },
  {
    id: 'se_attack_debuff_minor', // New (for Pulso Tóxico)
    name: 'Ataque Reduzido (P)',
    description: 'Ataque reduzido em 10%.',
    icon: 'fas fa-hand-fist text-slate-300 opacity-60',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(-0.10),
    baseDurationTurns: 2,
  },
  {
    id: 'se_frozen_stun',
    name: 'Congelado',
    description: 'Pula o próximo turno.',
    icon: 'fas fa-snowflake text-sky-300 animate-pulse',
    type: 'debuff',
    effectType: 'stun',
    baseDurationTurns: 1,
  },
  {
    id: 'se_disoriented_accuracy_debuff', // New
    name: 'Desorientado',
    description: 'Precisão reduzida em 25%.',
    icon: 'fas fa-compass-slash text-orange-400',
    type: 'debuff',
    effectType: 'stat_change_multiply', 
    statToChange: 'accuracyMultiplier',
    changeValue: new Decimal(0.75), // Multiplier (1 - 0.25)
    baseDurationTurns: 2,
  },
  {
    id: 'se_blurred_vision_accuracy_debuff', // New
    name: 'Visão Embaçada',
    description: 'Precisão drasticamente reduzida (-50%).',
    icon: 'fas fa-eye-low-vision text-gray-400',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'accuracyMultiplier',
    changeValue: new Decimal(0.50), // Multiplier (1 - 0.50)
    baseDurationTurns: 2,
  },
  {
    id: 'se_max_hp_reduction_battle_debuff', // New
    name: 'Vitalidade Drenada',
    description: 'HP máximo reduzido para esta batalha.',
    icon: 'fas fa-heart-crack text-red-700',
    type: 'debuff',
    effectType: 'stat_change_add', // Applied once, affects maxHP
    statToChange: 'maxHp',
    changeValue: new Decimal(-10), // Placeholder, actual value set by ability effect
    baseDurationTurns: 99, // Battle long
  },
  {
    id: 'se_delay_turn_short', // New for Ovo de Cascalho
    name: 'Turno Atrasado',
    description: 'A próxima ação deste ovo será atrasada ou pulada.',
    icon: 'fas fa-hourglass-end text-yellow-600',
    type: 'debuff',
    effectType: 'stun', // Functionally similar to a short stun
    baseDurationTurns: 1,
  },
  {
    id: 'se_attack_debuff_15_2t', // New for Ovo de Coral
    name: 'Ataque Reduzido (Coral)',
    description: 'Ataque reduzido em 15%.',
    icon: 'fas fa-hand-fist text-teal-300 opacity-70',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(-0.15),
    baseDurationTurns: 2,
  },
  {
    id: 'se_bleeding_3dmg_2t', // New for Ovo de Medula
    name: 'Sangramento Leve',
    description: 'Sofre 3 de dano por turno.',
    icon: 'fas fa-tint text-red-600',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 2,
    baseTickValue: new Decimal(3),
    tickIntervalTurns: 1,
  },
   { // New for Ovo Sussurrante
    id: 'se_confused_50_miss_2t',
    name: 'Confuso',
    description: '50% de chance de errar o alvo por 2 turnos.',
    icon: 'fas fa-question-circle text-orange-400 animate-spin',
    type: 'debuff',
    effectType: 'custom_logic', // Logic handled in ability execution
    baseDurationTurns: 2,
  },
  { // New for Ovo Sussurrante
    id: 'se_psychic_echo_5dmg_on_ability_3t',
    name: 'Eco Psíquico',
    description: 'Recebe 5 de dano ao usar qualquer habilidade por 3 turnos.',
    icon: 'fas fa-head-side-cough text-purple-400',
    type: 'debuff',
    effectType: 'custom_logic', // Logic handled in ability execution
    baseDurationTurns: 3,
    baseTickValue: new Decimal(5), // Store damage value here
  },
  { // New for Ovo Esquelético
    id: 'se_bleeding_6dmg_2t',
    name: 'Sangramento (Esquelético)',
    description: 'Sofre 6 de dano por turno.',
    icon: 'fas fa-tint text-red-700',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 2,
    baseTickValue: new Decimal(6),
    tickIntervalTurns: 1,
  },
  { // New for Ovo de Musgo
    id: 'se_speed_debuff_30_2t_moss',
    name: 'Velocidade Reduzida (Musgo)',
    description: 'Velocidade reduzida em 30%.',
    icon: 'fas fa-ankh text-green-700 opacity-70',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'speed',
    changeValue: new Decimal(-0.30),
    baseDurationTurns: 2,
  },
  { // New for Ovo da Centelha
    id: 'se_paralysis_1t_spark',
    name: 'Paralisado (Centelha)',
    description: 'Não pode realizar ações neste turno.',
    icon: 'fas fa-bolt text-yellow-600 animate-pulse',
    type: 'debuff',
    effectType: 'stun',
    baseDurationTurns: 1,
  },
  { // Epic - Ovo Umbroso: Dreno de Luz
    id: 'se_accuracy_debuff_25_2t',
    name: 'Visão Reduzida',
    description: 'Precisão reduzida em 25%.',
    icon: 'fas fa-eye-slash text-gray-400',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'accuracyMultiplier',
    changeValue: new Decimal(0.75), // Attacker's accuracy becomes 75% of normal
    baseDurationTurns: 2,
  },
  { // Epic - Ovo Psíquico: Confusão Neural
    id: 'se_action_confusion_40_1t',
    name: 'Confusão Neural',
    description: '40% de chance de atacar um alvo aleatório (aliado ou inimigo) por 1 turno.',
    icon: 'fas fa-question-circle text-orange-400 animate-spin',
    type: 'debuff',
    effectType: 'action_inversion_random_target',
    baseDurationTurns: 1,
    changeValue: new Decimal(0.40), // Chance for confusion
  },
  { // Epic - Ovo Psíquico: Clarividência
    id: 'se_enemy_effectiveness_reduced_50_1t',
    name: 'Efetividade Reduzida',
    description: 'Efetividade da próxima habilidade reduzida em 50%.',
    icon: 'fas fa-arrow-down-wide-short text-blue-400',
    type: 'debuff',
    effectType: 'effectiveness_reduction',
    changeValue: new Decimal(0.50), // Multiplier for effectiveness
    baseDurationTurns: 1,
  },
  { // Epic - Ovo Obsidiano: Fúria Contida (Vulnerabilidade)
    id: 'se_self_damage_taken_increase_15_2t',
    name: 'Fúria Contida (Vulnerável)',
    description: 'Recebe +15% de dano.',
    icon: 'fas fa-exclamation-triangle text-red-300',
    type: 'debuff', // Considered a debuff because it's a negative effect on self
    effectType: 'stat_change_multiply',
    statToChange: 'incomingDamageMultiplier',
    changeValue: new Decimal(1.15), // Takes 115% damage
    baseDurationTurns: 2,
  },
  { // Epic - Ovo Obsidiano: Fúria Contida (Explosão Pendente)
    id: 'se_delayed_explosion_marker_30dmg_2t',
    name: 'Fúria Contida (Explosão Pendente)',
    description: 'Explodirá causando 30 de dano AoE após 2 turnos.',
    icon: 'fas fa-bomb text-red-400 animate-pulse',
    type: 'buff', // From caster's perspective, it's a pending beneficial effect
    effectType: 'delayed_aoe_damage',
    baseTickValue: new Decimal(30), // Damage amount
    baseDurationTurns: 2,
  },
  {
    id: 'se_cooldown_lock_1t',
    name: 'Bloqueio de Recarga',
    description: 'Não pode usar habilidades que entram em recarga por 1 turno.',
    icon: 'fas fa-hourglass-end text-orange-500',
    type: 'debuff',
    effectType: 'ability_lock', 
    baseDurationTurns: 1,
  },
  {
    id: 'se_ruin_stacking_dot',
    name: 'Ruína',
    description: 'Sofre 5 de dano por acúmulo no início do turno. Aumenta o dano de Explosão Cadavérica.',
    icon: 'fas fa-skull-crossbones text-purple-600',
    type: 'debuff',
    effectType: 'damage_over_time',
    baseDurationTurns: 99, 
    baseTickValue: new Decimal(5), 
    tickIntervalTurns: 1,
    isStackable: true,
    maxStacks: 10, 
  },
  {
    id: 'se_silence_abyssal_1t',
    name: 'Silêncio Abissal',
    description: 'Não pode usar habilidades por 1 turno.',
    icon: 'fas fa-microphone-alt-slash text-slate-400',
    type: 'debuff',
    effectType: 'ability_lock',
    baseDurationTurns: 1,
  },
  {
    id: 'se_abyssal_corrosion_dot_percent',
    name: 'Corrosão Abissal',
    description: 'Sofre dano igual a 8% do HP máximo no início do turno por 3 turnos.',
    icon: 'fas fa-water-lower text-blue-800',
    type: 'debuff',
    effectType: 'damage_over_time', 
    baseDurationTurns: 3,
    baseTickValue: new Decimal(0.08), 
    tickIntervalTurns: 1,
  },
  {
    id: 'se_stats_swapped_chimera',
    name: 'Atributos Trocados',
    description: 'Atributos base temporariamente trocados com o Ovo Quimérico.',
    icon: 'fas fa-exchange-alt text-pink-400',
    type: 'debuff', 
    effectType: 'custom_logic', 
    baseDurationTurns: 2,
  },


  // --- Buffs ---
  {
    id: 'se_defense_buff_minor',
    name: 'Defesa Aumentada (P)',
    description: 'Defesa aumentada em 30%.',
    icon: 'fas fa-shield-alt text-green-400',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(0.30),
    baseDurationTurns: 3,
  },
  {
    id: 'se_defense_buff_major',
    name: 'Defesa Aumentada (M)',
    description: 'Defesa aumentada em 50%.',
    icon: 'fas fa-shield-alt text-green-500 ring-1 ring-green-300 rounded-full',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(0.50),
    baseDurationTurns: 3,
  },
  {
    id: 'se_attack_buff_minor',
    name: 'Ataque Aumentado (P)',
    description: 'Ataque aumentado em 25%.',
    icon: 'fas fa-hand-fist text-red-400', 
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(0.25),
    baseDurationTurns: 3,
  },
  {
    id: 'se_ghoul_presence_caster_buff',
    name: 'Presença Carniçal',
    description: 'Um carniçal auxiliará em combate pelos próximos 2 turnos.',
    icon: 'fas fa-skull text-purple-400',
    type: 'buff',
    effectType: 'custom_summon_attack', 
    baseDurationTurns: 2, 
  },
  {
    id: 'se_sap_barrier_shield',
    name: 'Barreira de Seiva',
    description: 'Absorve até 25 de dano.',
    icon: 'fas fa-leaf text-emerald-400',
    type: 'buff',
    effectType: 'shield',
    shieldValue: new Decimal(25), 
    baseDurationTurns: 3, 
  },
  {
    id: 'se_team_damage_reduction_buff',
    name: 'Muralha Protetora', 
    description: 'Reduz o dano recebido pela equipe em 20%.',
    icon: 'fas fa-users-cog text-sky-400', 
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'incomingDamageMultiplier',
    changeValue: new Decimal(0.80), 
    baseDurationTurns: 2,
  },
  {
    id: 'se_energy_mirror_reflect_buff', // New
    name: 'Espelho de Energia',
    description: 'Reflete 30% do dano recebido de volta ao atacante.',
    icon: 'fas fa-shield-reflect text-cyan-300', // Custom icon idea
    type: 'buff',
    effectType: 'damage_reflection_percentage',
    reflectionPercentage: new Decimal(0.30),
    baseDurationTurns: 2,
  },
  {
    id: 'se_evasion_buff_major', // New
    name: 'Esquiva Aumentada',
    description: '+40% chance de esquivar de ataques.',
    icon: 'fas fa-person-running text-blue-300',
    type: 'buff',
    effectType: 'stat_change_add', // Additive to dodge chance
    statToChange: 'dodgeChance',
    changeValue: new Decimal(0.40),
    baseDurationTurns: 2,
  },
  {
    id: 'se_guaranteed_evasion_buff', // New
    name: 'Esquiva Garantida',
    description: 'Esquiva do próximo ataque recebido.',
    icon: 'fas fa-ghost text-white',
    type: 'buff',
    effectType: 'guaranteed_evasion',
    baseDurationTurns: 1, // Lasts until hit or 1 turn
  },
  {
    id: 'se_initiative_plus_buff', // New
    name: 'Iniciativa+',
    description: 'Age com prioridade no próximo turno.',
    icon: 'fas fa-stopwatch-20 text-yellow-300',
    type: 'buff',
    effectType: 'stat_change_add', // Will be a large temporary speed boost
    statToChange: 'speed',
    changeValue: new Decimal(1000), // Large temporary speed boost
    baseDurationTurns: 1, // Only for the next turn's calculation
  },
  {
    id: 'se_defense_buff_25_2t', // New for Ovo de Cascalho
    name: 'Fortificação Rústica',
    description: 'Defesa aumentada em 25%.',
    icon: 'fas fa-mountain text-green-500',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(0.25),
    baseDurationTurns: 2,
  },
  {
    id: 'se_speed_buff_20_2t', // New for Ovo Cinético
    name: 'Deslocamento Rápido',
    description: 'Velocidade aumentada em 20%.',
    icon: 'fas fa-bolt text-yellow-300',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'speed',
    changeValue: new Decimal(0.20),
    baseDurationTurns: 2,
  },
  {
    id: 'se_team_damage_reduction_20_1t', // New for Ovo de Coral
    name: 'Manto Protetor',
    description: 'Reduz o dano recebido pela equipe em 20% por 1 turno.',
    icon: 'fas fa-shield-heart text-teal-300',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'incomingDamageMultiplier', // This affects how much damage is taken
    changeValue: new Decimal(0.80), // Target takes 80% of normal damage
    baseDurationTurns: 1,
  },
  {
    id: 'se_evasion_buff_30_1t', // New for Ovo de Medula
    name: 'Alerta de Perigo',
    description: '+30% chance de esquivar de ataques.',
    icon: 'fas fa-exclamation-triangle text-yellow-300',
    type: 'buff',
    effectType: 'stat_change_add',
    statToChange: 'dodgeChance',
    changeValue: new Decimal(0.30),
    baseDurationTurns: 1,
  },
  { // New for Ovo Esquelético (Self-debuff part of ability)
    id: 'se_self_defense_debuff_10_2t_skeletal',
    name: 'Casca Rachada (Defesa Red.)',
    description: 'Defesa reduzida em 10%.',
    icon: 'fas fa-shield-slash text-red-300',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(-0.10),
    baseDurationTurns: 2,
  },
  { // New for Ovo Esquelético (Self-buff part of ability)
    id: 'se_self_attack_buff_30_2t_skeletal',
    name: 'Casca Rachada (Ataque Aum.)',
    description: 'Ataque aumentado em 30%.',
    icon: 'fas fa-axe-battle text-green-400',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(0.30),
    baseDurationTurns: 2,
  },
  { // New for Ovo de Musgo
    id: 'se_regen_6hp_3t',
    name: 'Regeneração Leve',
    description: 'Restaura 6 HP por turno.',
    icon: 'fas fa-heart-pulse text-lime-400',
    type: 'buff',
    effectType: 'heal_over_time',
    baseDurationTurns: 3,
    baseTickValue: new Decimal(6),
    tickIntervalTurns: 1,
  },
  { // New for Ovo Petrificado
    id: 'se_active_immobility_dmg_reduct_50_1t_skip_turn',
    name: 'Imobilidade Ativa',
    description: 'Recebe 50% menos dano, mas não pode agir no próximo turno.',
    icon: 'fas fa-rock text-stone-400',
    type: 'buff', // It's a buff due to damage reduction, stun is the drawback
    effectType: 'stat_change_multiply', 
    statToChange: 'incomingDamageMultiplier',
    changeValue: new Decimal(0.50), // Takes 50% damage
    baseDurationTurns: 1, // Damage reduction for 1 turn, stun handled by ability
  },
  { // New for Ovo Petrificado
    id: 'se_defense_buff_40_2t_petrified',
    name: 'Casca de Basalto',
    description: 'Defesa aumentada em 40%.',
    icon: 'fas fa-shield-halved text-stone-300',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'defense',
    changeValue: new Decimal(0.40),
    baseDurationTurns: 2,
  },
  { // Epic - Ovo Umbroso: Cobertura Sombria
    id: 'se_team_damage_reduction_20_2t',
    name: 'Cobertura Sombria (Buff)',
    description: 'Aliados recebem -20% de dano.',
    icon: 'fas fa-users-shield text-slate-300',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'incomingDamageMultiplier',
    changeValue: new Decimal(0.80),
    baseDurationTurns: 2,
  },
  { // Epic - Ovo Obsidiano: Reflexão Obsidiana
    id: 'se_damage_reflection_50_1t',
    name: 'Reflexão Obsidiana (Buff)',
    description: 'Reflete 50% do dano recebido neste turno.',
    icon: 'fas fa-gem text-black',
    type: 'buff',
    effectType: 'damage_reflection_percentage',
    reflectionPercentage: new Decimal(0.50),
    baseDurationTurns: 1,
  },
  // Expedition Boss Effects
  {
    id: 'se_vulnerable_cycle',
    name: 'Vulnerável',
    description: 'Recebe dano dobrado de todas as fontes.',
    icon: 'fas fa-heart-crack text-red-400',
    type: 'debuff',
    effectType: 'stat_change_multiply',
    statToChange: 'incomingDamageMultiplier',
    changeValue: new Decimal(2),
    baseDurationTurns: 2,
  },
  {
    id: 'se_reflective_cycle',
    name: 'Reflexivo',
    description: 'Reflete 100% do dano recebido de volta ao atacante.',
    icon: 'fas fa-shield-reflect text-cyan-300',
    type: 'buff',
    effectType: 'damage_reflection_percentage',
    reflectionPercentage: new Decimal(1),
    baseDurationTurns: 2,
  },
  {
    id: 'se_guardian_fury_attack',
    name: 'Fúria do Guardião (ATK)',
    description: 'Ataque aumentado em 10% por acúmulo.',
    icon: 'fas fa-fist-raised text-orange-400',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(0.10),
    baseDurationTurns: 99,
    isStackable: true,
    maxStacks: 5,
  },
  {
    id: 'se_guardian_fury_speed',
    name: 'Fúria do Guardião (VEL)',
    description: 'Velocidade aumentada em 10% por acúmulo.',
    icon: 'fas fa-person-running text-yellow-400',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'speed',
    changeValue: new Decimal(0.10),
    baseDurationTurns: 99,
    isStackable: true,
    maxStacks: 5,
  },
  {
    id: 'se_chrono_form_past',
    name: 'Forma: Passado',
    description: 'Defesa massivamente aumentada, velocidade reduzida.',
    icon: 'fas fa-shield-alt text-gray-400',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 2,
  },
  {
    id: 'se_chrono_form_present',
    name: 'Forma: Presente',
    description: 'Velocidade aumentada, prioriza ataques em área.',
    icon: 'fas fa-bolt text-yellow-400',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 2,
  },
  {
    id: 'se_chrono_form_future',
    name: 'Forma: Futuro',
    description: 'Imprevisível, aplica buffs aleatórios em si mesmo.',
    icon: 'fas fa-dice-d20 text-purple-400',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 2,
  },
  {
    id: 'se_relic_damage_boost',
    name: 'Poder da Relíquia',
    description: '+10% Dano',
    icon: 'fas fa-sword',
    type: 'buff',
    effectType: 'stat_change_multiply',
    statToChange: 'attack',
    changeValue: new Decimal(0.1),
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_on_death_explode',
    name: 'Instável',
    description: 'Explode ao morrer, causando 15 de dano a todos os inimigos.',
    icon: 'fas fa-bomb',
    type: 'debuff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_on_death_poison',
    name: 'Esporos Finais',
    description: 'Aplica Veneno a todos os inimigos ao morrer.',
    icon: 'fas fa-skull-crossbones',
    type: 'debuff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_regen_5hp',
    name: 'Regeneração',
    description: 'Regenera 5 de HP por turno.',
    icon: 'fas fa-heart-pulse',
    type: 'buff',
    effectType: 'heal_over_time',
    baseDurationTurns: 99,
    baseTickValue: new Decimal(5),
  },
  {
    id: 'se_custom_dodge_50',
    name: 'Esquivo',
    description: '50% de chance de esquivar de ataques e habilidades.',
    icon: 'fas fa-ghost',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_immune_dots_stuns',
    name: 'Impassível',
    description: 'Imune a Sangramento, Veneno e Atordoamento.',
    icon: 'fas fa-shield-halved',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_stacking_attack',
    name: 'Poder Crescente',
    description: 'Ganha +10% de ataque por turno.',
    icon: 'fas fa-arrow-trend-up',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_cycle_states',
    name: 'Ciclo de Batalha',
    description: 'Alterna entre estados de vulnerabilidade e reflexão.',
    icon: 'fas fa-infinity',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  {
    id: 'se_custom_crit_reflect',
    name: 'Eco Crítico',
    description: 'Reflete 25% do dano recebido de acertos críticos.',
    icon: 'fas fa-undo-alt text-orange-400',
    type: 'buff',
    effectType: 'custom_logic',
    baseDurationTurns: 99,
  },
  // Placeholder
  {
    id: 'placeholder_undefined_status',
    name: 'Efeito Desconhecido',
    description: 'Este efeito de status não foi definido.',
    icon: 'fas fa-question-circle text-slate-500',
    type: 'debuff', 
    effectType: 'stun', 
    baseDurationTurns: 1,
  },
];